(function(){
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const menu=$('.menu-toggle'), nav=$('.nav'); if(menu) menu.addEventListener('click',()=>nav.classList.toggle('open'));
const list=$('#eventList'), grid=$('#calendarGrid'), title=$('#calendarTitle');
let current=new Date(2026,8,1), activeFilter='all';
const monthName=d=>d.toLocaleString('en-US',{month:'long',year:'numeric'});
const fmtDate=s=>new Date(s+'T12:00:00').toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'});
function openEvent(e){const m=$('#eventModal'); if(!m)return; $('#modalCategory').textContent=e.category.toUpperCase();$('#modalTitle').textContent=e.title;$('#modalDate').textContent='♡ '+fmtDate(e.date);$('#modalTime').textContent='◷ '+e.time;$('#modalLocation').textContent='⌖ '+e.location;$('#modalDescription').textContent=e.description;$('#modalSource').href=e.source;m.classList.add('show');m.setAttribute('aria-hidden','false');document.body.classList.add('modal-open')}
function closeModal(){const m=$('#eventModal');if(m){m.classList.remove('show');m.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open')}}
$$('[data-close]').forEach(x=>x.addEventListener('click',closeModal));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
function renderList(){if(!list)return;const shown=EVENTS.filter(e=>activeFilter==='all'||e.category===activeFilter).sort((a,b)=>a.date.localeCompare(b.date));list.innerHTML=shown.map(e=>{const d=new Date(e.date+'T12:00:00');return `<button class="event-card" data-id="${e.id}"><div class="event-date"><strong>${d.getDate()}</strong><span>${d.toLocaleString('en-US',{month:'short'})}</span></div><div class="event-info"><span class="tag">${e.category}</span><h3>${e.title}</h3><p>◷ ${e.time}</p><p>⌖ ${e.location}</p></div><span class="event-arrow">→</span></button>`}).join('')||'<p class="empty">No events in this category yet. Check back soon ♡</p>';$$('.event-card').forEach(b=>b.addEventListener('click',()=>openEvent(EVENTS.find(e=>e.id==b.dataset.id))));}
function renderCalendar(){if(!grid)return;const y=current.getFullYear(),m=current.getMonth();title.textContent=monthName(current);grid.innerHTML='';const first=new Date(y,m,1).getDay(),total=new Date(y,m+1,0).getDate();for(let i=0;i<first;i++)grid.appendChild(document.createElement('div'));for(let n=1;n<=total;n++){const key=`${y}-${String(m+1).padStart(2,'0')}-${String(n).padStart(2,'0')}`, matches=EVENTS.filter(e=>e.date===key);const c=document.createElement('button');c.className='calendar-day'+(matches.length?' has-event':'');c.innerHTML=`<span>${n}</span>${matches.length?'<b>♥</b>':''}`;if(matches.length)c.addEventListener('click',()=>openEvent(matches[0]));grid.appendChild(c)}}
if($('#prevMonth'))$('#prevMonth').onclick=()=>{current.setMonth(current.getMonth()-1);renderCalendar()};if($('#nextMonth'))$('#nextMonth').onclick=()=>{current.setMonth(current.getMonth()+1);renderCalendar()};
$$('.filter').forEach(b=>b.addEventListener('click',()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeFilter=b.dataset.filter;renderList()}));
renderList();renderCalendar();
})();
